### ISSUE TITLE
Ore gen

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/1.8.9-Realistic-Terrain-Generation#43]
A few people have reported that ore gen isn't working.

I've left some comments here:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1858

**Comment by topisani** [comment]
i have now experienced the chunk line with a lot of ores too

**Comment by srs-bsns** [comment]
> i have now experienced the chunk line with a lot of ores too

I've experienced this once now too, but unfortunately I'm dumb, and accidentally deleted that world when I was cleaning up my save directory. I didn't even get any screenshots of it. :\

It seemed that all ore generation was all packed into a single line. I don't know if it was just 1 chunk wide or wider, because I had quit the game to try and localise biome generation with BiomeTweaker, which is when the accidental deletion occured, and I haven't been able to reproduce it since.

On both sides of the 'line' there was no ore gen at all. That includes all ores, and all pockets of dirt, gravel, andesite, diorite, and granite.

Furthermore, regardless of not being able to reproduce this 'line' of ore, what I have observed is that there is an issue with ore generation in desert (desert, desert hills), savanna (savanna, savanna plateau), taiga (taiga, taiga hills, etc..), and extreme hills (emeralds still generate, but that's not a part of normal ore gen, but normal ore gen should still happen here).

Not every instance of the above biomes were void of ores, atleast not in the single-biome worlds I test with them (ID-2 desert, ID-35 savanna), nor in worlds where I only had a few biomes generating with BiomeTweaker.

Since I've never seen anything like this in 1.7.10, I'm assuming this is from one of the changes made in 1.8.*

**Comment by topisani** [comment]
Dirt and stone Pockets are generated at the same time/with the same code as ores, so that's not surprising. And I did have to make some changes to that code that I knew were very hacky, and I had plans to replace it, but must have forgotten. I'll look into it

**Comment by srs-bsns** [comment]
> Dirt and stone Pockets are generated at the same time

Yeah, they were all packed in with the ores. It almost seemed like there was some kind of broken iteration going on.

**Comment by srs-bsns** [comment]
User image from MCF for reference:
![](http://media-minecraftforum.cursecdn.com/attachments/187/456/635926802510700953.png)

**Comment by srs-bsns** [comment]
[MCF #1862](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1862)

RTG-1.8.9-0.0.3, default configs
Seed: 7553165326249679290
Coords: x=-2400 z=0
the line of ore is within 2 chunks (wide)

![](http://www.nihilism.ca/minecraft/20160307-RTG1.8.9-Issue43/RTG1.8.9-Issue-%2343-1.png)
![](http://www.nihilism.ca/minecraft/20160307-RTG1.8.9-Issue43/RTG1.8.9-Issue-%2343-2.png)

**Comment by whichonespink44** [comment]
Thanks srs - I'm gonna take a look at this tonight and see if we can get to the bottom of it.

**Comment by topisani** [comment]
yeah me too

**Comment by whichonespink44** [comment]
I'm only seeing coal and iron... were there any others in there that you noticed?

**Comment by topisani** [comment]
theres redstone at the bottom

**Comment by topisani** [comment]
and gravel and dirt

**Comment by whichonespink44** [comment]
*puts glasses on*

ahh yes, and gold and lapis :stuck_out_tongue_winking_eye:

**Comment by whichonespink44** [comment]
Ok, I *might* have fixed this in b86c5ad - initial testing in several worlds (including seed 7553165326249679290) showed all ores generating as normal. However, I didn't use any fancy tools to confirm this - all I did was dig down to level 12 and branch mine for a couple minutes in several locations within each world, including the coords listed above, and everything seemed alright.

**Comment by whichonespink44** [comment]
Fixed in b86c5ad
